In [19]:
import pandas as pd
import numpy as np
import pickle

from sklearn import tree

In [3]:
dataset=pd.read_csv(r'C:\python data science\data_visualization\Classification\play_tennis.csv')
display(dataset)

def lower_case(x):
    x=x.lower()
    return x

def lower_case_all(dataset):
    dataset['outlook']=dataset['outlook'].apply(lower_case)
    dataset['temp']=dataset['temp'].apply(lower_case)
    dataset['humidity']=dataset['humidity'].apply(lower_case)
    dataset['wind']=dataset['wind'].apply(lower_case)
    dataset['play']=dataset['play'].apply(lower_case)
    return dataset

def convert_to_text(y):
    if(y[0]==0):
        y='No'
    else:
        y='yes'
    
    return y
def numerize(x):
    if x=='sunny' or x=='hot' or x=='high' or x=='weak' or x=='no':
        x=0
    elif x=='overcast' or x=='mild' or x=='normal' or x=='strong' or x=='yes':
        x=1
    elif x=='rain' or x=='cool':
        x=2
    return x
def numerize_all(dataset):
    dataset['outlook']=dataset['outlook'].apply(numerize)
    dataset['temp']=dataset['temp'].apply(numerize)
    dataset['humidity']=dataset['humidity'].apply(numerize)
    dataset['wind']=dataset['wind'].apply(numerize)
    dataset['play']=dataset['play'].apply(numerize)
    return dataset

dataset=lower_case_all(dataset)
print('Converting to lower case:')
display(dataset)

print('Converting to numbers only:')
dataset=numerize_all(dataset)
display(dataset)

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

Converting to lower case:

    day   outlook  temp humidity    wind play
0    D1     sunny   hot     high    weak   no
1    D2     sunny   hot     high  strong   no
2    D3  overcast   hot     high    weak  yes
3    D4      rain  mild     high    weak  yes
4    D5      rain  cool   normal    weak  yes
5    D6      rain  cool   normal  strong   no
6    D7  overcast  cool   normal  strong  yes
7    D8     sunny  mild     high    weak   no
8    D9     sunny  cool   normal    weak  yes
9   D10      rain  mild   normal    weak  yes
10  D11     sunny  mild   normal  strong  yes
11  D12  overcast  mild     high  strong  yes
12  D13  overcast   hot   normal    weak  yes
13  D14      rain  mild     high  strong   no

Converting to numbers only:

    day  outlook  temp  humidity  wind  play
0    D1        0     0         0     0     0
1    D2        0     0         0     1     0
2    D3        1     0         0     0     1
3    D4        2     1         0     0     1
4    D5        2     2         1     0     1
5    D6        2     2         1     1     0
6    D7        1     2         1     1     1
7    D8        0     1         0     0     0
8    D9        0     2         1     0     1
9   D10        2     1         1     0     1
10  D11        0     1         1     1     1
11  D12        1     1         0     1     1
12  D13        1     0         1     0     1
13  D14        2     1         0     1     0

In [4]:
X=np.array(dataset.drop(['play','day'],axis=1)) #axis=1 for column 0 for rows
Y=np.array(dataset['play']).reshape(-1,1)

display(X)
display(Y)

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [2, 1, 0, 0],
       [2, 2, 1, 0],
       [2, 2, 1, 1],
       [1, 2, 1, 1],
       [0, 1, 0, 0],
       [0, 2, 1, 0],
       [2, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [2, 1, 0, 1]])

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]])

<h2> Training Model

In [5]:
model=tree.DecisionTreeClassifier()
model=model.fit(X,Y)

<h2> Saving Model

In [6]:
pickle.dump(model,open('decision_tree_model','wb')) #pickle is used to save machine learning model wb=write binary

<h2>Loading Model

In [7]:
model=pickle.load(open('decision_tree_model','rb'))

<h2>Taking Inputs

In [31]:
parameters=['Outlook','Temperature','Humidity','Wind']
inputs=[]
for i in parameters:
    inputs.append(input('enter value for'+i+': '))

inputs=[[numerize(i.lower()) for i in inputs]]
y=convert_to_text(model.predict(inputs))
print(y)

NameError: name 'numerize' is not defined

<h2>divided and divisior

In [60]:
import pandas as pd
import random

divided=[random.randint(1,100) for i in range(1,20000)]
divisor=[random.randint(1,100) for i in range(1,20000)]
op=[]
for div, divr in zip(divided,divisor):
    if div%divr==0:
        op.append(1)
    else:
        op.append(0)

data_to_save=pd.DataFrame(columns=['Divided','Divisor','op'])
data_to_save['Divided']=divided
data_to_save['Divisor']=divisor
data_to_save['op']=op
data_to_save.to_csv('dataset_new.csv',index=False)

def convert_to_text(y):
    if(y[0]==0):
        y='Not Divided'
    else:
        y='Divided'
    
    return y

In [74]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
dataset1=pd.read_csv(r'C:\python data science\data_visualization\Classification\dataset_new.csv')
X2=dataset1.drop(columns=['op'],axis=1)
Y2=dataset1['op']
X_train,X_test,Y_train,Y_test=train_test_split(X2,Y2)
display(dataset1)

       Divided  Divisor  op
0            2       28   0
1           44       26   0
2           91       39   0
3           57       59   0
4           10       54   0
...        ...      ...  ..
19994       31       82   0
19995       87       68   0
19996       72       78   0
19997       48       66   0
19998       77        8   0

[19999 rows x 3 columns]

In [75]:
X1=np.array(dataset1.drop(['op'],axis=1)) #axis=1 for column 0 for rows

Y1=np.array(dataset1['op']).reshape(-1,1)
display(X1)
display(Y1)

array([[ 2, 28],
       [44, 26],
       [91, 39],
       ...,
       [72, 78],
       [48, 66],
       [77,  8]])

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [78]:
model1=tree.DecisionTreeClassifier()
model1=model1.fit(X_train,Y_train)
Y_preds=model.predict(X_test)
print(accuracy_score(Y_train,Y_preds))

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(

ValueError: X has 2 features, but DecisionTreeClassifier is expecting 3 features as input.

In [70]:
pickle.dump(model1,open('decision_tree_model1','wb'))

In [71]:
model1=pickle.load(open('decision_tree_model1','rb'))

In [72]:
parameters=['Divided','Divisor']
inputs=[]
for i in parameters:
    inputs.append(input('enter value for'+i+': '))

inputs=[inputs for i in inputs]
y2=convert_to_text(model1.predict(inputs))
print(y2)

Not Divided